# ***Escalar - Dimensión 0***

In [11]:
import numpy as np
escalar = np.array(42)

print(type(escalar))
print(escalar)

<class 'numpy.ndarray'>
42


# ***Vector - Dimensión 1***

In [12]:
vector = np.array([30,29,35,31,33,36,42])
print(vector)

[30 29 35 31 33 36 42]


# ***Matriz - 2 dimensiones***

In [21]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


 # ***Tensor - 3 a n dimensiones***

In [22]:
tensor = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(tensor)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


***Rango***

In [23]:
array_range = np.arange(10)
print(array_range)

[0 1 2 3 4 5 6 7 8 9]


***Identidad***

In [24]:
eye_matrix = np.eye(5)
print(eye_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


***Diagonal***

In [26]:
diag = np.diag([1,2,3,4,5,6,7])
print(diag)

[[1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]
 [0 0 0 0 0 0 7]]


***Random***

In [79]:
random = np.random.random((2,3))
print(random)

[[0.94371949 0.96999927 0.17633768]
 [0.83536869 0.6349637  0.78049076]]
