In [2]:
import numpy as np

array = np.array([10,20,30,40,50])
print(array[1])
print(array[-1])

20
50


In [3]:
print(array[1:4])

[20 30 40]


In [5]:
print(array[1:7])
print(array[-1:-7])

[20 30 40 50]
[]


In [7]:
bool_index = array > 25
print(bool_index)
print(type(bool_index))

[False False  True  True  True]
<class 'numpy.ndarray'>


In [8]:
index = [2,0,4]
print(array[index])

[30 10 50]


In [55]:
array = np.random.randint(1, 10, size=(3, 3))
print(array)
print(array[0,1]) # Valor en fila 0, columna 1

# Siempre primero las filas, despues las columnas


[[8 3 4]
 [6 6 6]
 [7 9 7]]
3


In [56]:
print(array[:2, :2])

[[8 3]
 [6 6]]


# 1 - Acceder a elementos específicos:
*Crea un arreglo de 10 números y accede al cuarto y penúltimo elemento usando índices positivos y negativos.*

In [57]:
array = np.array([1,2,3,4,5,6,7,8,9,0])
print(array[3])
print(array[-2])

4
9


# 2 - Slicing de arreglos:
*Dado un arreglo de números del 1 al 20, extrae los elementos entre las posiciones 3 y 7, y luego los elementos de las últimas 5 posiciones.*

In [58]:
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(array[3:6])
print(array[-5:]) 

[4 5 6]
[16 17 18 19 20]


# 3 - Indexing con booleanos:
*Crea un arreglo de números aleatorios entre 0 y 100. Usa una expresión booleana para acceder solo a los números mayores a 50.*

In [59]:
array = np.random.randint(0, 100, size=10)
bool_mascara = array > 50
mayores_50 = array[bool_mascara]
print(mayores_50)

[73 52 64]


# 4 - Indexación con múltiples índices:
*Dado un arreglo de 8 elementos, crea una lista de índices para acceder a los elementos en las posiciones 1, 4, y 6.*

In [60]:
array = np.array([1,2,3,4,5,6,7,8])
index_array = np.array([1,4,6])
print(array[index_array])

[2 5 7]


# 5 - Matrices bidimensionales:
*Genera una matriz 4x4 de números aleatorios entre 10 y 50, y accede a la submatriz de 2x2 ubicada en la esquina inferior derecha.*

In [ ]:
matrix = np.random.randint(10, 50, size=(4, 4))
print(matrix)
matrix_2x2 = matrix[-2, -2]
print(matrix_2x2)

[[19 19 46 13]
 [45 42 42 31]
 [35 25 33 19]
 [22 10 33 32]]
[[19 19]
 [45 42]]
