In [5]:
import numpy as np

prices = np.array([100,200,300])
discount = np.array([0.9])

discount_prices = prices * discount
print(discount_prices)

[ 90. 180. 270.]


In [10]:
prices = np.random.randint(100, 500, size=(3, 3))
discount = np.array([10,20,30])

discount_prices = prices - discount
print(prices)
print("")
print(discount_prices)

[[284 117 312]
 [401 175 340]
 [317 189 272]]

[[274  97 282]
 [391 155 310]
 [307 169 242]]


In [12]:
array = np.array([1,2,3,4,5])
print(np.all(array > 3))

False


In [13]:
print(np.any(array > 4))

True


In [15]:
array_a = np.array([1,2,3])
array_b = np.array([4,5,6])

concatenated = np.concatenate((array_a, array_b))
print(concatenated)

[1 2 3 4 5 6]


In [19]:
stacked_v = np.vstack((array_a, array_b))
stacked_h = np.hstack((array_a, array_b))
print(stacked_v)
print("")
print(stacked_h)

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]


In [20]:
array_c = np.arange(1, 10)
split_array = np.split(array_c, 3)

print(array_c)
print(split_array)

[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [33]:
matrix_a = np.array([1,2,3,4,5,6,7,8,9]).reshape(3, 3)
split_matrix_a = np.split(matrix_a, 3)
print(matrix_a)
print(split_matrix_a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
