In [2]:
import numpy as np

survey_responses = np.array(["bueno", "excelente", "malo", "bueno",
                              "bueno", "malo", "malo", "bueno",
                              "excelente", "malo"])

print(np.unique(survey_responses))

['bueno' 'excelente' 'malo']


In [3]:
unique_elements, counts = np.unique(survey_responses, return_counts=True)
print(unique_elements, counts)

['bueno' 'excelente' 'malo'] [4 2 4]


In [12]:
# Slicing básico (View)

array_1 = np.arange(10)
view_1 = array_1[1:3]

print(array_1)
print(view_1)

array_1[1:3] = [10,11]
print(array_1)
print(view_1)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[10 11]


In [13]:
# Fancy Indexing (Copy)

array_x = np.arange(5, 10)
copy_x = array_x[[1,2]]

print(array_x)
print(copy_x)

array_x[1:3] = [10, 11]

print(array_x)
print(copy_x)

[5 6 7 8 9]
[6 7]
[ 5 10 11  8  9]
[6 7]


In [18]:
# Cómo saber si es un Copy o un View

print(view_1.base is array_1) # Devuelve True si es una vista del original
print(copy_x.base is array_x)

print(view_1.base is None) 
print(copy_x.base is None) # Devuelve True si es un objeto independiente

True
False
False
True
