***Calculos matriciales***

In [6]:
import numpy as np

A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

print(A)
print(B)
print()

# SUMA
sum = A + B
print(sum)

# RESTA
resta = A - B
print(resta)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [7]:
# MULTIPLICACION
product = np.dot(A, B)
print(product)

[[19 22]
 [43 50]]


In [14]:
# DETERMINANTE
A = np.array([[1,2], [3,4]])
det_A = np.linalg.det(A).astype(np.float32)
print(det_A)
print()
inv_A = np.linalg.inv(A).astype(np.float32)
print(inv_A)

-2.0

[[-2.   1. ]
 [ 1.5 -0.5]]


*Resolver Ax = b*

In [16]:
b = np.array([9,11])
x = np.linalg.solve(A,b)
print(x)

[-7.  8.]
