# Ejercicio: Análisis de Ventas Mensuales con NumPy

El objetivo de este ejercicio es trabajar con arrays de NumPy para analizar y
manipular datos de ventas de tres productos a lo largo de un año.
A través de diversas operaciones, explorarás cómo usar NumPy para obtener estadísticas,
realizar manipulaciones avanzadas y
aplicar técnicas de indexación para extraer información clave.

***

**Paso 1:** Crear Arrays con Datos de Ventas

Usa la librería numpy para crear los siguientes arrays: meses: un array con los nombres
de los meses del año.
ventas_A, ventas_B, ventas_C: arrays que representan las ventas mensuales de
tres productos diferentes.

In [106]:
import numpy as np

meses = np.array([
    'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 
    'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'
])

ventas_a = np.array([150, 200, 250, 300, 220, 210, 180, 190, 230, 240, 280, 300])
ventas_b = np.array([180, 210, 230, 250, 270, 260, 240, 250, 270, 290, 310, 330])
ventas_c = np.array([200, 220, 240, 260, 280, 300, 320, 340, 360, 380, 400, 420])

**Paso 2:** Estadísticas Básicas

Calcula la media y la suma de ventas para los productos A, B y C usando las funciones de NumPy.
Imprime estos valores en el formato siguiente:
Media de ventas Producto A: <valor>
Suma de ventas Producto A: <valor>
Repite para los productos B y C.

In [107]:
suma_a = np.sum(ventas_a).astype(np.int64)
promedio_a = np.mean(ventas_a).astype(np.float64)
suma_b = np.sum(ventas_b).astype(np.int64)
promedio_b = np.mean(ventas_b).astype(np.float64)
suma_c = np.sum(ventas_c).astype(np.int64)
promedio_c = np.mean(ventas_c).astype(np.float64)

print("Suma de producto A: ", suma_a,"- Promedio de venta A: ",promedio_a)
print("Suma de producto B: ", suma_b,"- Promedio de venta B: ",promedio_b)
print("Suma de producto C: ", suma_c,"- Promedio de venta C: ",promedio_c)

Suma de producto A:  2750 - Promedio de venta A:  229.16666666666666
Suma de producto B:  3090 - Promedio de venta B:  257.5
Suma de producto C:  3720 - Promedio de venta C:  310.0


**Paso 3:** Manipulación y Análisis de Datos

Total de ventas por mes: Suma las ventas de los tres productos para cada mes.
Promedio de ventas por producto: Calcula el promedio de ventas por producto.
Mes con mayor y menor ventas: Identifica qué mes tuvo el total de ventas más alto y cuál el más
bajo usando las funciones np.argmax y np.argmin.

In [108]:
# Total de ventas por mes
ventas_totales_mes = ventas_a + ventas_b + ventas_c

# Promedio total de venta
promedio_total_venta = (ventas_totales_mes / 3)

# Mes con mayor y menor venta
mayor_venta = np.argmax(ventas_totales_mes)
menor_venta = np.argmin(ventas_totales_mes)

print(f"Total de ventas: {ventas_totales_mes}")
print(f"Promedio total de venta: {promedio_total_venta}")
print(f"Mes con mayor venta: {mayor_venta}")
print(f"Mes con menor venta: {menor_venta}")

Total de ventas: [ 530  630  720  810  770  770  740  780  860  910  990 1050]
Promedio total de venta: [176.66666667 210.         240.         270.         256.66666667
 256.66666667 246.66666667 260.         286.66666667 303.33333333
 330.         350.        ]
Mes con mayor venta: 11
Mes con menor venta: 0


**Paso 4:** Operaciones Avanzadas con NumPy

Reshape y Transposición:

Crea una matriz 2D con las ventas de los tres productos y transforma su forma (reshape) a un array
tridimensional con dimensiones (3, 4, 3).
Transpone la matriz de ventas para que las filas se conviertan en columnas.
Invertir arrays: Invierte las ventas de cada producto en orden de meses.
Aplanar la matriz: Convierte la matriz de ventas a un array unidimensional.

In [125]:
# vstack para agrupar arrays en una matriz vertical
matriz_ventas = np.vstack([ventas_a, ventas_b, ventas_c])
print(matriz_ventas)
print()

# reshape a un array tridimencional (3,4,3)
matriz_ventas_3d = matriz_ventas.reshape(3, 4, 3)
print(matriz_ventas_3d)
print()

# transposición del reshape
matriz_ventas_3d_traspuesta = matriz_ventas_3d.T
print(matriz_ventas_3d_traspuesta)
print()

# se invierten las ventas de cada producto en orden de meses
ventas_a_inverted = ventas_a[::-1]
ventas_b_inverted = ventas_b[::-1]
ventas_c_inverted = ventas_c[::-1]

print(ventas_a_inverted)
print(ventas_b_inverted)
print(ventas_c_inverted)
print()

# Apalar la matriz (convertirla en unidimensional)
matriz_plana = matriz_ventas.flatten()
print(matriz_plana)


[[150 200 250 300 220 210 180 190 230 240 280 300]
 [180 210 230 250 270 260 240 250 270 290 310 330]
 [200 220 240 260 280 300 320 340 360 380 400 420]]

[[[150 200 250]
  [300 220 210]
  [180 190 230]
  [240 280 300]]

 [[180 210 230]
  [250 270 260]
  [240 250 270]
  [290 310 330]]

 [[200 220 240]
  [260 280 300]
  [320 340 360]
  [380 400 420]]]

[[[150 180 200]
  [300 250 260]
  [180 240 320]
  [240 290 380]]

 [[200 210 220]
  [220 270 280]
  [190 250 340]
  [280 310 400]]

 [[250 230 240]
  [210 260 300]
  [230 270 360]
  [300 330 420]]]

[300 280 240 230 190 180 210 220 300 250 200 150]
[330 310 290 270 250 240 260 270 250 230 210 180]
[420 400 380 360 340 320 300 280 260 240 220 200]

[150 200 250 300 220 210 180 190 230 240 280 300 180 210 230 250 270 260
 240 250 270 290 310 330 200 220 240 260 280 300 320 340 360 380 400 420]


**Paso 5:** Análisis de Elementos Únicos

Utiliza np.unique para encontrar los elementos únicos en los datos de ventas y cuenta cuántas
veces aparece cada uno.

In [ ]:
# busco los valores unicos, y su contador
valores_unicos, counts = np.unique(matriz_ventas, return_counts=True)
print(valores_unicos, counts)

# apilo en v los dos arrays, formando una matriz de 2x22
matriz_valores_unicos = np.vstack([valores_unicos, counts])
print(matriz_valores_unicos)

# traspongo la matriz de 2x22 para que me quede una de 22x2
matriz_contador_valores_unicos = matriz_valores_unicos.T
print()
print(matriz_contador_valores_unicos)

[150 180 190 200 210 220 230 240 250 260 270 280 290 300 310 320 330 340
 360 380 400 420] [1 2 1 2 2 2 2 3 3 2 2 2 1 3 1 1 1 1 1 1 1 1]
[[150 180 190 200 210 220 230 240 250 260 270 280 290 300 310 320 330 340
  360 380 400 420]
 [  1   2   1   2   2   2   2   3   3   2   2   2   1   3   1   1   1   1
    1   1   1   1]]

[[150   1]
 [180   2]
 [190   1]
 [200   2]
 [210   2]
 [220   2]
 [230   2]
 [240   3]
 [250   3]
 [260   2]
 [270   2]
 [280   2]
 [290   1]
 [300   3]
 [310   1]
 [320   1]
 [330   1]
 [340   1]
 [360   1]
 [380   1]
 [400   1]
 [420   1]]


**Paso 6:** Indexación y Slicing

Ventas del primer trimestre: Extrae las ventas de los tres primeros meses del año.
Indexación booleana: Selecciona los meses donde el total de ventas de los tres productos supere los 800.
Selección avanzada: Usa una lista de índices para seleccionar las ventas de los meses pares
(o selecciona los meses a tu elección) y muestra esas ventas en una nueva matriz.

In [139]:
# calculo ventas en los primeros 3 meses del año
ventas_primeros_3meses = (ventas_totales_mes[:3])
print(ventas_primeros_3meses)

# indexación booleana
ventas_mayores_a_800 = ventas_totales_mes[ventas_totales_mes > 800]
print(ventas_mayores_a_800)

# Selección avanzada
indice_meses_pares = [1,3,5,7,9,11]
ventas_meses_pares = ventas_totales_mes[indice_meses_pares]
print(ventas_meses_pares)

[530 630 720]
[ 810  860  910  990 1050]
[ 630  810  770  780  910 1050]
